<?php
	view::content();
	echo Form::open();
?>
<center>
    <table>
        <tr>
            <th>Departamento:</th><td> <?php echo Form::text('departamentos.nomb_dep',"maxlength='100' size='30'"); ?></td>
        </tr>
        
<?php echo Form::hidden('departamentos.id'); ?>
</table></center>

<center><?php echo Form::submit('aceptar'); echo Form::close(); ?>
<br>
<?php 
	echo Html::link("departamentos/lists/1", 'Vet Lista de departamentos'); ?>
</center>