<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<?php Tag::css('krisley')?>
<?php //Tag::css('pickadate')?>
<?php Tag::css('jquery-ui-1.8.13.custom') ?>
<?php Tag::css('../javascript/extjs4.2/resources/css/ext-all')?>
<?php echo Tag::js('jquery/jquery+kumbiaphp.min')?>
<?php echo Tag::js('jquery/jquery.min')?>
<?php //echo Tag::js('datepicker/datepicker')?>
<?php echo Tag::js('jquery/jquery.autocomplete')?>
    <?php echo Tag::js('jquery/jquery-1.5.1.min')?>
<?php echo Tag::js('jquery/jquery-ui-1.8.13.custom.min')?>
<?php echo Tag::js('js/combos')?>
<?php //echo Tag::js('datepicker/lang/es')?>
<?php echo Tag::js('extjs4.2/ext-all-debug')?>
<?php echo Tag::js('js/row-editing')?>
    <?php echo Tag::js('js/row-editingdespacho')?>

<?php echo Html::includeCss()?>
    

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Almacen MPPTT</title>
<meta name="keywords" content="Business Website, free templates, website templates, 3-column layout, CSS, XHTML" />
<meta name="description" content="Business Website, 3-column layout, free CSS template from templatemo.com" />


</head>

    <body><div align="center">
    <img src="<?php echo $site. '/public/img/minfra/img03.png'?>">
    </img>
    </div>
<div id="templatemo_container">
   
    <div id="templatemo_header">
    	<div id="logosection">
	        <div class="sitelogo"></div>
        	<div class="sitename">            	
            	<span></span>            </div>
      </div>
        <div id="header">
            
            <div class="title">
            	
	        	<span class="bigtext">Departamento de Almacén</div>

        </div>
	</div>
    
	<div id="templatemo_menu">
    	<div id="search">
				
    	</div>
        <div id="menu">

        </div>
	</div>
    
    <!-- start of content -->
    
	<div id="templatemo_content">
    
    	<!-- start of left column -->
    
    	<div id="templatemo_left_column">        	

            <div id="leftcolumn_box01">
                <div class="leftcolumn_box01_top">
                    <h2>Usuario Actual:</h2>
                </div>
                <div class="leftcolumn_box01_bottom">
		    <?php echo Session::get('usuario');

                    ?>
                </div>            
            </div>
            
            <div id="leftcolumn_box02">
            	<h2>Menu</h2>
                <ul>
                    <li><a href="<? echo $site . 'cargos/create/'?>" target="_parent">Cargos</a></li>
                    <li><a href="<? echo $site . 'unidades/create/'?>" target="_parent">Unidades</a></li>
                    <li><a href="<? echo $site . 'articulos/create/'?>" target="_parent">Articulos</a></li>
                    <li><a href="<? echo $site . 'departamentos/create/'?>" target="_parent">Departamento</a></li>
                    <li><a href="<? echo $site . 'empleados/create/'?>" target="_parent">Empleado</a></li>
                    <li><a href="<? echo $site . 'requisiciones/create/'?>" target="_parent">Requisicion</a></li>
                    <li><a href="<? echo $site . 'despachos/create/'?>" target="_parent">Despachos</a></li>
                    <li><a href="<? echo $site . 'usuarios/create/'?>" target="_parent">Usuarios</a></li>
                    <li>                    
                        <?php if(Session::get('usuario')){?>
                        <a href="<? echo $site . 'usuarios/salir/'?>">Salir</a>
                    <?php }?>
                    </li>
                </ul>
            </div>
            
			<div id="imagebutton">
            	
			</div>
            
        </div>
        
        <!-- end of left column -->
        
        <!-- start of middle column -->
        
        <div id="templatemo_middle_column" align="center">
        
        	
                <p align="center">
             <?php View::content(); ?>

            </p> <br />
            
            <!--<div id="section1">
            	
          </div>
            
            <div id="section2">
                <div class="section2_top">
                    
                </div>
                <div class="section2_bottom">
			      
                    <div class="more_button"></div>
            	</div>
            </div>
            -->
        </div>
        
        <!-- end of middle column -->
        
        <!-- start of right column -->

        
        
        <!-- end of right column -->
    
    </div>
    
    <!-- end of content -->
        
        
	<div id="templatemo_footer">
        <a href="#">Home</a> | <a href="#">About Us</a> | <a href="#">Services</a> | <a href="#">Solutions</a> | <a href="#">Contact Us</a><br />
        Copyright ©  <a href="#">Your Company Name</a> | Designed by <a href="http://www.templatemo.com" target="_blank">templatemo.com</a></div>
    <div id="templatemo_footer_bottom"></div>

</div>
</body>
</html>
